male(santanu).
female(satyavati).
female(ganga).
male(bhishma).
male(vichitraveera).
female(chitrangada).
female(ambalika).
female(ambika).
male(pandu).
male(dritarashtra).
female(kunti).
female(madri).
male(karna).
male(godsurya).
male(yudhisthira).
male(arjuna).
male(bhima).
male(nakula).
male(sahadeva).
male(madresan).
male(salya).
male(subala).
male(sakuni).
male(dussasan).
male(duryodhan).
male(yuyutsu).
male(lakshan).
male(jayadratha).
male(suratha).
male(vrudhakshatra).
female(gandhari).
female(vysalady).
female(dushala).
female(bhanumati).
female(draupati).
female(devaki).
female(baladhara).
female(hidimbi).
female(subhadra).
female(ulupi).
female(chitra).
female(renuka).
female(vijaya).
male(drupad).
male(pratividhya).
male(sutasoma).
male(srutasoma).
male(sataneeka).
male(srutakarma).
male(abhimanyu).
male(ghatotkacha).
male(drishtadyumn).
female(drupadwife).
female(subalawife).
female(madresanwife).
married(santanu,satyavati).
married(satyavati,santanu).
married(santanu,ganga).
married(ganga,santanu).
child(bhishma,ganga).
child(bhishma,santanu).
child(vichitraveera,satyavati).
child(vichitraveera,santanu).
child(chitrangada,satyavati).
child(chitrangada,santanu).
married(ambalika,vichitraveera).
married(vichitraveera,ambalika).
married(vichitraveera,ambika).
married(ambika,vichitraveera).
child(dritarashtra,ambika).
child(dritarashtra,vichitraveera).
child(pandu,ambalika).
child(pandu,vichitraveera).
married(pandu,madri).
married(madri,pandu).
married(pandu,kunti).
married(kunti,pandu).
child(karna,kunti).
child(karna,godsurya).
child(yudhisthira,kunti).
child(yudhisthira,pandu).
child(bhima,kunti).
child(bhima,pandu).
child(arjuna,kunti).
child(arjuna,pandu).
child(nakula,madri).
child(nakula,pandu).
child(sahadeva,pandu).
child(sahadeva,madri).
married(draupati,nakula).
married(nakula,draupati).
married(renuka,nakula).
married(nakula,renuka).
married(draupati,sahadeva).
married(sahadeva,draupati).
married(vijaya,sahadeva).
married(sahadeva,vijaya).
child(srutakarma,draupati).
child(srutakarma,sahadeva).
child(sataneeka,draupati).
child(sataneeka,nakula).
married(yudhisthira,draupati).
married(draupati,yudhisthira).
married(devaki,yudhisthira).
married(yudhisthira,devaki).
married(bhima,draupati).
married(draupati,bhima).
married(bhima,baladhara).
married(baladhara,bhima).
married(hidimbi,bhima).
married(bhima,hidimbi).
married(draupati,arjuna).
married(arjuna,draupati).
married(subhadra,arjuna).
married(arjuna,subhadra).
married(ulupi,arjuna).
married(arjuna,ulupi).
married(chitra,arjuna).
married(arjuna,chitra).
child(pratividhya,draupati).
child(pratividhya,yudhisthira).
child(sutasoma,draupati).
child(sutasoma,bhima).
child(ghatotkacha,hidimbi).
child(ghatotkacha,bhima).
child(srutasoma,arjuna).
child(srutasoma,draupati).
child(abhimanyu,subhadra).
child(abhimanyu,arjuna).
child(draupati,drupad).
child(drishtadyumn,drupad).
married(vysalady,dritarashtra).
married(dritarashtra,vysalady).
married(dritarashtra,gandhari).
married(gandhari,dritarashtra).
child(gandhari,subala).
child(sakuni,subala).
child(yuyutsu,vysalady).
child(yuyutsu,dritarashtra).
child(duryodhan,gandhari).
child(duryodhan,dritarashtra).
child(dussasan,gandhari).
child(dussasan,dritarashtra).
child(dushala,gandhari).
child(dushala,dritarashtra).
married(bhanumati,duryodhan).
married(duryodhan,bhanumati).
child(lakshan,bhanumati).
child(lakshan,duryodhan).
married(jayadratha,dushala).
married(dushala,jayadratha).
child(jayadratha,vrudhakshatra).
child(suratha,jayadratha).
married(drupad,drupadwife).
married(drupadwife,drupad).
child(draupati,drupadwife).
child(drishtadyumn,drupadwife).
married(subala,subalawife).
married(subalawife,subala).
child(sakuni,subalawife).
child(gandhari,subalawife).
married(madresan,madresanwife).
married(madresanwife,madresan).
child(madri,madresan).
child(madri,madresanwife).
child(salya,madresan).
child(salya,madresanwife).
father(X,Y):-child(Y,X),male(X).
mother(X,Y):-child(Y,X),female(X).
parent(X,Y):-child(Y,X).
spouse(X,Y):-married(X,Y).
husband(X,Y):-male(X),spouse(X,Y).
wife(X,Y):-female(X),spouse(X,Y).
son(X,Y):-male(X),child(X,Y).
daughter(X,Y):-female(X),child(X,Y).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(Z,Y),ancestor(X,Z).
grandparent(X,Y):-parent(Z,Y),parent(X,Z).
greatgrandparent(X,Y):-parent(P,Y),grandparent(X,P).
grandfather(X,Y):-grandparent(X,Y),male(X).
grandmother(X,Y):-grandparent(X,Y),female(X).
matGrandma(X,Y) :- mother(X,P), mother(P,Y).
patGrandma(X,Y) :- mother(X,P), father(P,Y).
matGrandpa(X,Y) :- father(X,P), mother(P,Y).
patGrandpa(X,Y) :- father(X,P), father(P,Y).
fatherinlaw(X,Y):-married(Z,Y),parent(X,Z),male(X).
motherinlaw(X,Y):-married(Z,Y),parent(X,Z),female(X).
descendent(X,Y):-ancestor(Y,X).
wife(X,Y)
